# Conclusion

In this project, we analyzed both the Regional impact of hosting the Olympics on a country’s economic and tourism indicators. To better understand the Regional effects, we also included observations on the National level. We drew conclusions on a country by country basis:      
     
<b>The United Kingdom: </b>      
There was a large amount of economic heterogeneity. While tourism data showed more regional distinction, we did not find that any changes intra-region could be attributed to the Olympics.     

<b>Canada: </b>    
Although there was growth in tourism within Vancouver following the 2010 Olympics, we did not find any differential effects on economic outcomes across different regions within British Columbia or Canada, suggesting that economic growth after 2010 could not be attributed to the Olympics.      

<b>Brazil: </b>    
Extensive analysis of indicators for economic and tourism data demonstrated through both observation and statistical measurements that there were no meaningful changes that could be attributed to the Olympics on the regional level.   

By analyzing GDP, income, unemployment rate and tourism, we found that there is no significant difference in regional economic impacts of hosting Olympics on the three countries. Although there appear to be increases in tourism, GDP and income for all three countries after hosting the Olympics, it is not clear that these increases were any greater for the regions where the Olympics were hosted than in other regions in these countries. The majority of regional time series follow the same pattern as the national one.         

In the future, we believe additional work can be done in this direction by collecting and analyzing more indicators and performing additional statistical tests. Specifically, we think one could further explore the breakdown of GDP by industries as well as perform statistical tests that can determine whether the Olympics had a statistically significant impact, as most of our analysis is done by inspection. We hope to see these topics explored in the future.       
    
